### ISSUE TITLE
Mod does not function. Missing DLL.

### ISSUE THREAD

**Issue by adrianfc2010** [Colon-D/webfishing-gun#1]
Log states as follows

[WRN] Assembly at C:\Program Files (x86)\Steam\steamapps\common\WEBFISHING\GDWeave\mods\webfishing_gun\webfishing_gun.dll does not exist

Checked all files in the repository. The file the log states is missing is not present anywhere in the repository. As a result the mod fails to load.

**Comment by Colon-D** [comment]
The file is inside the ZIP file in the Releases section of the repository. You were presumably looking at the Code section, which does not include the dll file since you compile it from the code.
Here is a direct link to the Release: https://github.com/Colon-D/webfishing-gun/releases/download/1.0.0/webfishing_gun.zip
I can confirm the mod works with the latest version of its requirements, ie Webfishing v1.09, GDWeave 2.0.14.0, and Lure 4.2.0.
Let me know how you get on.

**Comment by Colon-D** [comment]
I'll assume you got it working.

**Comment by adrianfc2010** [comment]
Yep. My appologies for not responding earlier. Been a busy work week.

Sorry about the confusion there. I guess I had gotten so used to the repository's home page including the releases I completely forgot about there being a link to that section on the side. Thanks for the reminder, I deservedly feel like an idiot. ^.^'

Can confirm that the mod is working although I have not had a chance to test it in multiplayer yet.
